version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.18.5
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - /gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:3000"
      - "222:22"


version: '3.3'
services:

    #serveur de base de donnees
    database:
      image: 'mariadb:10.3'
      container_name: database
      restart: always
      environment:
          MYSQL_USER: quoi
          MYSQL_PASSWORD: feur
          MYSQL_DATABASE: api
          MYSQL_ROOT_PASSWORD: rootpassword
        
      ports:
          - '3306:3306'
      volumes:
          - /mariadb/:/var/lib/mysql/