#!/bin/bash

sudo useradd quoi -m -s /bin/bash
echo "feur" | sudo passwd --stdin quoi

#Install de gitea 
su quoi
wget -O gitea https://dl.gitea.com/gitea/1.18.5/gitea-1.18.5-linux-amd64
chmod +x gitea

# Définir les autorisations pour l'utilisateur "quoi" sur les fichiers spécifiques
sudo setfacl -R -m u:quoi:rw– /gitea:/data
sudo setfacl -R -m u:quoi:rw– /etc/timezone:/etc/localtime
sudo setfacl -R -m u:quoi:rw– /mariadb/:/var/lib/mysql/

#Creation du dossier dans gitea pour les docckers compose
mkdir /gitea/dockconf

sudo usermod -aG docker quoi

#Git pull la conf docker
git pull https://github.com/Chenishere/Projetinfrab2.git 


# Docker-compose
sudo docker-compose up -d




# Partie firewall 
iptables -F

iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP

iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT


iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# Autorise le SSH (22 car par default)
iptables -A INPUT -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -p tcp --sport 22 -j ACCEPT

# Autorise HTTP et HTTPS
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -A INPUT -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -p tcp --sport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --sport 443 -j ACCEPT

# Autorise DNS
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A INPUT -p udp --sport 53 -j ACCEPT






# Partie Fail2ban

# Installation de fail2ban
apt-get install -y fail2ban

# Création d'une copie du fichier de configuration d'origine
cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local

# Configuration du fichier jail.local
cat << EOF > /etc/fail2ban/jail.local
[DEFAULT]
bantime = 3600
banaction = iptables-multiport
destemail = yanice.bousseria@ynov.com
sender = aymeric.lauvaud@ynov.com

[ssh]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
EOF

# Redémarrage du service fail2ban
service fail2ban restart

#Log
